template.md
Narlıderedeki iki uygun mekan eklendi.
=> Narlıdere 2 mekan eklendi

README.md
- Google maps link is provided.
- A category is added.
=> Moda İskelesi Kütüphanesi (aka Moda Pier)

README.md
=> added Cayyolu/Ankara

README.md
Emoji yüzünden yanlış verilen bağlantlar doğrularıyla değiştirildi.
=> Resolve #13

README.md
=> mersin ili verisi eklendi

README.md
İdealtepe nocknockcoffee eklendi.
=> İstanbul için yeni veri girildi.

README.md
Trabzon şehri için bizzat gidip gördüğüm birkaç çalışma mekanı ekledim.
=> feat: add several places for Trabzon

README.md
Afyonkarahisar'da bulunan mekanları ekledim.
=> Added Afyonkarahisar

README.md
Afyonkarahisar'a yeni mekanlar eklendi.
=> Afyonkarahisar'a yeni mekanlar eklendi.

README.md
- markdownlint kurallarına göre düzenlendi.
- tablo hizalamaları yapıldı.
- eksik sütunlar eklendi
- boş satırlar N/A olarak değiştirildi
=> format & add missing columns

README.md
It is a nice cafe where I go to work often.
=> Beşiktaş - Coffee Talks Added

README.md
Aydın ili için ekleme yapıldı.
=> Aydın için ekleme yapıldı.

README.md
=> Removed CoffeeLog from Aydın

README.md
and Fixed the google URL of La Puerta Experience venue
=> cortado coffee added

README.md
[add: "Manisa Simit Dünyası - Sanayi" added.](https://github.com/acikkaynak/calisma-mekanlari/commit/3125eae30dbd648ec933415cab0c2278085fa8e9)
[optimize: Markdown style optimized.](https://github.com/acikkaynak/calisma-mekanlari/commit/acdaae6dbb5e46514f0b05c57cf7d690cd188dd6)
=> add: "Manisa Simit Dünyası - Sanayi" added.

.vscode/settings.json
=> add: defaultFormatter added.

README.md
This PR adds 8 places to the list: 5 Istanbul, 2 Antalya and 1 Mugla.
=> Add new places for Istanbul, Antalya and Mugla

README.md
Izmir/Menderes calisma mekani.
=> chore: new place to work for Izmir

README.md
eksik dev branchi ile mergelenen datanin geri alinmasi
=> revert #37ca98a

README.md
Istanbul and Izmir New Locations Added.
=> Update README.md with new working locations

README.md
* Update README.md with new working locations
* uptade to readme
=> Update README.md with new working locations (#76)
